name: Check Backend API

on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

jobs:
  test:
    name: Test API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install pnpm
        run: |
          npm install -g pnpm@9.15.4

      - name: Create .env.development file
        run: |
          echo "DB_HOST=localhost" >> backend/.env.development
          echo "DB_USER=root" >> backend/.env.development
          echo "DB_PASSWORD=011001" >> backend/.env.development
          echo "DB_NAME=meowsql" >> backend/.env.development


      - name: Install dependencies & test
        run: |
          pnpm install
          cd backend
          pnpm install
