name: check backend API

on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

jobs:
  # 不依赖其他作业的作业
  setup:
    name: Setup MySQL and Env
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: localhost

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MySQL environment
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV

      - name: Create .env.development.local in backend
        run: |
          mkdir -p backend  # 确保目标目录存在
          echo "DB_USER=${{ secrets.DB_USER }}" >> backend/.env.development.local
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> backend/.env.development.local
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> backend/.env.development.local
          echo "DB_HOST=localhost" >> backend/.env.development.local  # 修改为容器名称

  # 实际测试的作业
  test:
    name: Test API
    runs-on: ubuntu-latest
    needs: setup  # 依赖于 setup 作业
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: localhost

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install pnpm
        run: |
          npm install -g pnpm@9.15.4

      - name: Install dependencies and run tests
        run: |
          pnpm install
          cd backend
          pnpm install
          pnpm test
