name: Set up MySQL

jobs:
  mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_USER: ${{ secrets.DB_USER }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s  # 增加间隔时间
          --health-timeout=5s
          --health-retries=10  # 增加重试次数
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
